Fix Carthage build issue
Instagram/IGListKit pull request #1531
Opened 2021-09-15 14:34 UTC by cntrump

## Changes in this pull request

Issue fixed:
- Fix Carthage build issue.
- Remove useless Pod files.

### Checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I added tests, an experiment, or detailed why my change isn't tested.
- [x] I added an entry to the `CHANGELOG.md` for any breaking changes, enhancements, or bug fixes.
- [x] I have reviewed the [contributing guide](https://github.com/Instagram/IGListKit/blob/master/.github/CONTRIBUTING.md)

2021-09-15 14:38 UTC, cntrump commented
Cartfile
```
github "Instagram/IGListKit" "master"
```

Build 
```
carthage update --platform ios --use-xcframeworks
```

2021-09-23 17:21 UTC, lorixx requested changes
https://github.com/Instagram/IGListKit/pull/1531/checks?check_run_id=3666537897

Hi @cntrump looks like all the Unit tests are failing here, can you fix them and update your PR? Thanks

2021-09-24 03:20 UTC, cntrump commented
> https://github.com/Instagram/IGListKit/pull/1531/checks?check_run_id=3666537897
> 
> Hi @cntrump looks like all the Unit tests are failing here, can you fix them and update your PR? Thanks

Thanks for review, fixed and tested, https://github.com/cntrump/IGListKit/runs/3695497205?check_suite_focus=true

2021-09-25 18:43 UTC, lorixx commented
@cntrump  Fantastic! The CI run looks great and I am very happy that we got this fixed, I will land this PR on Monday, thanks again for your support to IGListKit!

2021-09-25 19:04 UTC, lorixx commented
@cntrump One follow-up question, do you know what was the issue before? and why deleting everything under Pods/ would solve the issue? Thanks!

2021-09-25 19:05 UTC, lorixx approved these changes

2021-09-25 19:05 UTC, lorixx commented on .github/workflows/CI.yml
> +        run: pod install
This makes a lot of sense to me now!

2021-09-25 22:49 UTC, cntrump commented
> @cntrump One follow-up question, do you know what was the issue before? and why deleting everything under Pods/ would solve the issue? Thanks!

Run `carthage build --platform ios --use-xcframeworks`

```
*** xcodebuild output can be found in /var/folders/5_/ymh1f63s1h93dc24x0y5g1rm0000gn/T/carthage-xcodebuild.KNu0Px.log
*** Building scheme "IGListKit" in IGListKitExamples.xcworkspace
```

Scheme "IGListKit" in IGListKitExamples.xcworkspace was built instead of IGListKit.xcodeproj.

`Pods`, `*.xcworkspace` and `*.lock` can be regenerated by running `bundle install` and `pod install`.

2021-09-30 23:04 UTC, closed without merging